name: 功能请求 / Feature request
title: "[Feature] "
description: 提出你的功能请求 / Propose your feature request
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## 在提交问题之前，请确认以下事项：
        1. 请 **确保** 您已经查阅了 [Sync Pointer Wiki](https://github.com/renzhenxuexi0/sync-pointer/wiki) 确认软件不存在类似的功能
        2. 请 **确保** [已有的问题](https://github.com/renzhenxuexi0/sync-pointer/issues?q=is%3Aissue) 中没有人提交过相似issue，否则请在已有的issue下进行讨论
        3. 请 **务必** 给issue填写一个简洁明了的标题，以便他人快速检索
        4. 请 **务必** 先下载 [Alpha](https://github.com/renzhenxuexi0/sync-pointer/releases/tag/alpha) 版本测试，确保该功能还未实现
        5. 请 **务必** 按照模板规范详细描述问题，否则issue将会被关闭
        ## Before submitting the issue, please make sure of the following checklist:
        1. Please make sure you have read the [Sync Pointer Wiki](https://github.com/renzhenxuexi0/sync-pointer/wiki) to confirm that the software does not have similar functions
        2. Please make sure there is no similar issue in the [existing issues](https://github.com/renzhenxuexi0/sync-pointer/issues?q=is%3Aissue), otherwise please discuss under the existing issue
        3. Please be sure to fill in a concise and clear title for the issue so that others can quickly search
        4. Please be sure to download the [Alpha](https://github.com/renzhenxuexi0/sync-pointer/releases/tag/alpha) version for testing to ensure that the function has not been implemented
        5. Please describe the problem in detail according to the template specification, otherwise the issue will be closed

  - type: textarea
    id: description
    attributes:
      label: 功能描述 / Feature description
      description: 详细清晰地描述你的功能请求 / A clear and concise description of what the feature is
    validations:
      required: true
  - type: textarea
    attributes:
      label: 使用场景 / Use case
      description: 请描述你的功能请求的使用场景 / Please describe the use case of your feature request
    validations:
      required: true
