/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFluentDismiss16Regular: typeof import('~icons/fluent/dismiss16-regular')['default']
    IFluentHome24Regular: typeof import('~icons/fluent/home24-regular')['default']
    IFluentMaximize16Regular: typeof import('~icons/fluent/maximize16-regular')['default']
    IFluentMinimize16Regular: typeof import('~icons/fluent/minimize16-regular')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TitleBar: typeof import('./components/title-bar/index.vue')['default']
  }
}
